schema {
  query: Query
  mutation: Mutation
}
type Mutation {
  register(password: String!, email: String!): UsersModel!
  createSection(input: SectionInputCreate!): SectionModel!
  editingSection(input: SectionInputCreate!, id: Float!): SectionModel!
  removeSection(id: Float!): SectionModel!
  addCinema(cinema: FilmsInputCreate!): FilmsModel!
  editingCinema(cinema: FilmsInputCreate!, id: Float!): FilmsModel!
  removeCinema(id: Float!): FilmsModel!
  addSerial(serial: FilmsInputCreate!): FilmsModel!
  editingSerial(serial: FilmsInputCreate!, id: Float!): FilmsModel!
  removeSerial(id: Float!): FilmsModel!
  addSeason(season: Float!, type: String!): SeasonEntity!
}

input SectionInputCreate {
  name: String!
  description: String!
}

input FilmsInputCreate {
  name: String!
  discription: String!
  genres: [String!]!
  miniPoster: Upload
  promoPoster: Upload
  promoVideo: Upload
  country: String!
  section: Float!
}

"""The `Upload` scalar type represents a file upload."""
scalar Upload
